steps:
  # Clean all cache and build artifacts to ensure fresh build
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Cleaning cache directories..."
        rm -rf dist .expo node_modules/.cache .cache
        echo "Cache cleaned successfully"
        
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install', '--legacy-peer-deps']
  
  # Verify environment variables
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building with EXPO_PUBLIC_API_URL=${_API_URL}"
        echo "EXPO_PUBLIC_ENV=production"
    
  # Build PWA for production with clear cache
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting production build with cache clear..."
        npx expo export --platform web --clear
    env:
      - 'EXPO_PUBLIC_API_URL=${_API_URL}'
      - 'EXPO_PUBLIC_APP_NAME=AI Agent'
      - 'EXPO_PUBLIC_APP_VERSION=1.0.0'
      - 'EXPO_PUBLIC_ENV=production'
    
  # Deploy to Firebase Hosting
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting --project ${_FIREBASE_PROJECT_ID} --non-interactive

substitutions:
  _API_URL: 'https://ai-agent-backend-1025750725266.us-central1.run.app'
  _FIREBASE_PROJECT_ID: 'professional-website-462321'
  
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
  
timeout: '1200s'
